spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: ${{secrets.JWT_SECRET}}

naver:
  openapi:
    client:
      id: ${{secrets.CLIENT_ID}}
      secret: ${{secrets.CLIENT_SECRET}}
