spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(3qbdNoLs1xfZnDOBC6jeeg==)
    password: ENC(qywyJ6KKRGqgYON3JE2Vp6iql1zNkBu0)
    url: ENC(uxzd1BnoRpDeqh3lmtUqbABX+urNhLclmI+d4gGNxhEMzKk6N9W1QUyHgAs6Gp08ClfLLCj3G7IryRJd51dqcMtKJANaYT6R)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: ENC(8AhBswZf/kCiZZmfFf019TZ0BgRPWrXozzRBQJFNZrvWzBBZ4DUbeUt0EZWPzRH4rSe+8x0l8yk=)

naver:
  openapi:
    client:
      id: ENC(HRkqW0kapzjRwwhzMEBrKeJCnDR5S/Mct6RBBDOt+B0=)
      secret: ENC(WiOZZWgarMe2DozKgHTklXQiXbnNCg/S)

jasypt:
  encryptor:
    password: ${SECRET}
