name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: ./gradlew build -Dspring.profiles.active=cloud,URL=${{secrets.URL}},CLIENT_ID=${{secrets.CLIENT_ID}},CLIENT_SECRET=${{secrets.CLIENT_SECRET}},JWT_SECRET=${{secrets.JWT_SECRET}},USERNAME=${{secrets.USERNAME}},PASSWORD=${{secrets.PASSWORD}}
